# Generated by Django 6.0 on 2025-12-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('berry', 'berry'), ('tropical', 'tropical'), ('citrus', 'citrus'), ('seeded', 'seeded'), ('coastal', 'coastal'), ('special', 'special'), ('superfood', 'superfood')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveBigIntegerField()),
                ('product_desc', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_image/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
