# Generated by Django 6.0 on 2025-12-27 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news_image/')),
                ('news_desc', models.TextField()),
                ('news_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
