# Generated by Django 6.0 on 2025-12-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_product_image_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='seller',
        ),
    ]
